export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_ERROR = 'FETCH_EMPLOYEE_ERROR';
export const ASSIGN_EMPLOYEE_SURVEY = 'ASSIGN_EMPLOYEE_SURVEY';
export const REMOVE_EMPLOYEE_SURVEY = 'REMOVE_EMPLOYEE_SURVEY';
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE';
